env:
  global:
    - secure: BtMqic4Yx+2mb3QTOua8tVZzdi2A1TlHIAmLOhnwGRyaIckJezdp3mpac/lcLLTAgBpZVVrAc8OFQlWBOvoquOtqdbsxmdsvkcNi6li+jKtOzy4q2plWkQWa7st0WLrHt2AHjpuls7UZDUoncn2Rp155IpAxNCa5x/FrJ7BmXwatMFRkXExT3ik7YAyNCV14FVgX5kMrh1YOkTz2N2NTuZiuXmX4Fta8WnpAKjLYT8fLFCE/tMcIHbx4mr/lfjXcK1dt+qEf+TK1RFMCYxEdwZYfFWAcu8RpX5uP1kfFFUenDGYE85WsEXjAXFIqCiVFQxl3HttYNUXAXOgUTxNbauTEdt5pSKkZXs9AqfkQ9nAjwGkcjl0nG+4KeW2RkCa0RDstEsPh6SCkT7MO5MqsT+w9agW9XQGK6qafM01BgUygqad1PkyR0OJBGI+bWH6MMMVeaCIFsbomA9dYxVq1bqjXRalzLCpmdVtxpHF8f1p4nIK/euys7c+HgdoClmqIAw9LBnkuclE/t1hl8aYCI8eKUUYyA8P/n/oEPHEgiDBOYCotDBSbN/V6ToiUnRuiaB5vi4fK6Gu5ycJnN1uNNCFpXfXpiUu77btK1crPXQMG6qYqxX0xkp11LDmEPpfAD94g0rJk3hBCheUMI0hPq+a0FddGVIxHgQP33t6YVNU=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/ZeroDot1_CoinBlockerLists_browser
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
